name: build

on:
  push

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04]
 
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install-dev
        shell: bash
        run: |
          pip install -e .[develop]

