name: build

on:
  push

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
 
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - id: cache-venv-linux
        uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: venv
          key: ${{ runner.os }}-venv-v2-${{ hashFiles('setup.py') }}

      - id: cache-venv-macos
        uses: actions/cache@v1
        if: startsWith(runner.os, 'macOS')
        with:
          path: venv
          key: ${{ runner.os }}-venv-v2-${{ hashFiles('setup.py') }}

      - id: cache-venv-windows
        uses: actions/cache@v1
        if: startsWith(runner.os, 'Windows')
        with:
          path: venv
          key: ${{ runner.os }}-venv-v2-${{ hashFiles('setup.py') }}

      - name: set-venv-path
        shell: bash
        run: |
          VENV_ACTIVATE_PATH="venv/bin/activate"
          if [ "${{startsWith(runner.os, 'Windows')}}" == "true" ]; then
            VENV_ACTIVATE_PATH="venv/Scripts/activate"
          fi
          echo "::set-env name=VENV_ACTIVATE_PATH::$VENV_ACTIVATE_PATH"

      - name: create-venv
        if: ${{steps.cache-venv-linux.outputs.cache-hit != 'true' && steps.cache-venv-macos.outputs.cache-hit != 'true' && steps.cache-venv-windows.outputs-cache-hit != 'true'}}
        shell: bash
        run: |
          python -m venv venv
          source $VENV_ACTIVATE_PATH
          pip install -e .[develop,pandas]

      - name: run-tests
        shell: bash
        run: |
         source $VENV_ACTIVATE_PATH
         nosetests --traverse-namespace -s tests/unit

  build:
    runs-on: ubuntu-18.04
    needs: test

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: package
        shell: bash
        run: |
          # todo detect release event see if this is prerelease or actual release
          PYPI_NAME=testpypi
          PYPI_REPO=https://test.pypi.org/legacy
          EXTENDED_VERSION_NUMBER=0.0.0
          VERSION=EXTENDED_VERSION_NUMBER
          # update version
          sed "s|\"latestVersion\":.*$|\"latestVersion\":\"$VERSION\",|g" synapseclient/synapsePythonClient > temp
          rm synapseclient/synapsePythonClient
          mv temp synapseclient/synapsePythonClient

          # ensure environment
          python3 -m pip install setuptools==38.6.0

          # install synapseclient
          python3 setup.py install

          # create distribution
          python3 setup.py sdist

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
            name: synapseclient-${VERSION}
            path: dist/*

